commerce_payment.commerce_payment_gateway.plugin.payu_payment:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    merchant_key:
      type: string
      label: 'Merchant Key'
    salt:
      type: string
      label: 'Salt'